# Generated by Django 5.0 on 2024-01-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='producttranslation',
            table='products_translation',
        ),
    ]
