# Generated by Django 5.0 on 2024-01-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_table_alter_producttranslation_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-updated_at',)},
        ),
    ]
